### ISSUE TITLE
Control of the Dolphin

### ISSUE THREAD

**Issue by Jens-Wymeersch** [0xAlon/dolphin#2]
Hi @0xAlon, I'm thinking of buying this device but I have questions :

- Are you happy with the device ? Any problems since you bought it ?
- I see you have only one switch in your integration. Why is that ? 

My use case is based on the temperature in the boiler and presence detection, how much electricity I need to add to ensure everyone has a shower but not too much. 

Regards,
Jens

**Comment by 0xAlon** [comment]
Hi @Jens-Wymeersch,

Excellent device, I had no problems since I bought it, and the installation process is straightforward.
The integration includes multiple entities such as six switches based on the number of showers to heat (The device knows how to calculate those parameters using ML), Sabbath mode, Thermostat temperature with the ability to set the thermostat temperature manually, and the on/off function.

There is also an excellent mobile application that offers additional options.

**Comment by Jens-Wymeersch** [comment]
@0xAlon super to hear. Is there a reason why you didn't add the other options into the integration ?

**Comment by 0xAlon** [comment]
@Jens-Wymeersch No, it's only a matter of time and demand.
